<form method='POST' action='index.php'>
    <fieldset>
        <label for="userEmail">Email</label>
        <input type="email" name="userEmail"/>
    </fieldset>
    <fieldset>
        <label for="userPassword">Mot de passe</label>
        <input type="password" name="userPassword"/>
    </fieldset>
    <fieldset class='sr-only'>
        <label for="formName"></label>
        <input type="text" name="formName"/>
    </fieldset>
    <fieldset>
        <button>Se connecter</button>
    </fieldset>
</form>