<footer>
    <section>
        <h2 class='sr-only'>
            <nav>
                <ul>
                    <li>
                        Accueil
                    </li>
                    <li>
                        Connexion
                    </li>
                    <li>
                        Création de compte
                    </li>
                </ul>
            </nav>            
        </h2>
    </section>
</footer>