<header>
    <section>
        <h2 class='sr-only'>
            <nav>
                <ul>
                    <li>
                        <a href="index.php?route=homepage">
                            Accueil
                        </a>
                    </li>
                    <li>
                        <a href="index.php?route=connexion">
                            Connexion
                        </a>
                    </li>
                    <li>
                        <a href="index.php?route=creer-un-compte">
                            Création de compte
                        </a>
                    </li>
                </ul>
            </nav>            
        </h2>
    </section>
</header>