<form method="POST" action="index.php">
    <fieldset>
        <label for="edit">Editer votre article :</label>
    </fieldset>
    <fieldset>
        <label for="edit-title">Editer le "titre de l'article" :</label>
        <input type="text" name="edit-title"/>
    </fieldset>
    <fieldset>
        <label for="edit-content">Editer l'article :</label>
        <input type="text" name="edit-content"/>
    </fieldset>
    <fieldset>
        <label for="edit-author">Editer l'auteur :</label>
        <input type="text" name="edit-author"/>
    </fieldset>
    <fieldset>
        <button>Envoyer</button>
    </fieldset>
</form>