<form method="POST" action="index.php">
    <fieldset>
        <label for="create">Créer votre article :</label>
    </fieldset>
    <fieldset>
        <label for="title">Titre de l'article</label>
        <input type="text" name="title"/>
    </fieldset>
    <fieldset>
        <label for="content">Votre article :</label>
        <input type="text" name="content"/>
    </fieldset>
    <fieldset>
        <label for="author">Auteur</label>
        <input type="text" name="author"/>
    </fieldset>
    <fieldset>
        <button>Envoyer</button>
    </fieldset>
</form>