<table>
    <thead>
        <th>
            <!-- title injecté en php-->
        </th>
    </thead>
    <tbody>
        <tr>
            <td>
                <!--content base de données posts-->
            </td>
            <td>
                <!--author base de données posts-->
            </td>
        </tr>
    </tbody>
    <?php
    require '_post-create.phtml';
    require '_post-edit.phtml';
    ?>
</table>