<!DOCTYPE html>
<html lang="fr" prefix="og: https://ogp.me/ns#">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Page admin</title>
      <link rel="stylesheet" href="assets/style/css/style.css">
    </head>
    <body>
        <?php
        require 'partials/_admin-header.phtml';
        
        var_dump($template);
        
        require $folder.'/'.$template.'.phtml';
        
        require 'partials/_admin-footer.phtml';
        ?>
    </body>
</html>