<form method="POST" action="index.php">
    <fieldset>
        <label for="name-categorie">Nom de la catégorie :</label>
        <input type="text" name="name-categorie"/>
    </fieldset>
    <fieldset>
        <label for="description-categorie">Votre article :</label>
        <input type="text" name="description-categorie"/>
    </fieldset>
    <fieldset>
        <button>Envoyer</button>
    </fieldset>
</form>