<table>
    <thead>
        <th>
            <!-- nom du post en php-->
        </th>
    </thead>
    <tbody>
        <tr>
            <td>
                <!--name base de données post_categories-->
            </td>
            <td>
                <!--description base de données post_categories-->
            </td>
        </tr>
    </tbody>
    <?php
    require '_post-category-create.phtml';
    require '_post-category-edit.phtml';
    ?>
</table>