<form method='POST' action='index.php'>
    <fieldset>
        <label for="firstName">Prénom :</label>
        <input type="text" name='firstName'>
    </fieldset>
    <fieldset>
        <label for="lastName">Nom de famille :</label>
        <input type="text" name="lastName"/>
    </fieldset>
    <fieldset>
        <label for="email">Votre email :</label>
        <input type="email" name="email"/>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password"/>
    </fieldset>
    <fieldset>
        <label for="confirmPassword">Confirmer votre mot de passe :</label>
        <input type="password" name="confirmPassword"/>
    </fieldset>
    <fieldset class='sr-only'>
        <label for="formName"></label>
        <input type="text" name=""/>
    </fieldset>
    <fieldset>
        <button>S'inscrire</button>
    </fieldset>
</form>