<header>
    <section>
        <h2 class='sr-only'>
            <nav>
                <ul>
                    <li>
                        <a href="index.php?route=admin-posts">
                            Liste des posts
                        </a>
                    </li>
                    <li>
                        <a href="index.php?route=admin-categories">
                            Liste des catégories
                        </a>
                    </li>
                    <li>
                        <a href="index.php?route=creer-un-compte">
                            Déconnexion
                        </a>
                    </li>
                </ul>
            </nav>            
        </h2>
    </section>
</header>